// This file was generated by Silwright.
// Source: lir.ndef
// Generated: 2026-07-13T13:40:23Z
// Do not modify this file directly; regenerate it from the source definition.

#pragma once

#include <memory>
#include <optional>
#include <string>
#include <variant>
#include <vector>
#include <cstddef>
#include <cstdint>
#include "symbol.hpp"

namespace lir
{

    enum class binary_op_t
    {
        Multiply,
        Division,
        Modulus,
        Plus,
        Minus,
        Equals,
        NotEquals,
        LessThan,
        LessThanEqual,
        GreaterThan,
        GreaterThanEqual,
        AndOp,
        OrOp,
        Shl,
        Shr
    };

    struct location;
    struct attributes;
    struct base_var;
    struct deref;
    struct field;
    struct place;
    struct number;
    struct char_literal;
    struct bool_literal;
    struct string_literal;
    struct allocate_record_expression;
    struct field_initialisation;
    struct load_expression;
    struct if_expression;
    struct function_call;
    struct cast_expression;
    struct unary_expression;
    struct binary_expression;
    struct return_statement;
    struct break_statement;
    struct expression_statement;
    struct store_string_statement;
    struct store_record_statement;
    struct store_statement;
    struct while_statement;
    struct function_head;
    struct function_definition;
    struct import_definition;
    struct global_definition;
    struct module;

    struct location
    {
        source_range location;
    };

    struct attributes
    {
        std::vector<std::string> attributes;
    };

    using place_elem = std::variant<deref, field>;

    using expr = std::variant<number, char_literal, bool_literal, string_literal, allocate_record_expression, load_expression, if_expression, function_call, cast_expression, unary_expression, binary_expression>;

    using statement = std::variant<return_statement, break_statement, expression_statement, store_string_statement, store_record_statement, store_statement, while_statement>;

    using expr_list = std::vector<std::unique_ptr<expr>>;

    using statement_list = std::vector<std::unique_ptr<statement>>;

    struct base_var
    {
        std::string name;
        symbol_id symbol_ref;
    };

    struct deref
    {
    };

    struct field
    {
        std::size_t index;
    };

    struct place
    {
        base_var base;
        std::vector<place_elem> projection;
    };

    struct number
    {
        long long value;
        type_id assigned_type;
    };

    struct char_literal
    {
        std::uint32_t ch;
    };

    struct bool_literal
    {
        bool value;
    };

    struct string_literal
    {
        std::size_t table_index;
        long long size;
    };

    struct allocate_record_expression
    {
        type_id type;
    };

    struct field_initialisation
    {
        std::size_t field_index;
        std::unique_ptr<expr> value;
    };

    struct load_expression
    {
        place source;
        type_id assigned_type;
    };

    struct if_expression
    {
        std::unique_ptr<expr> condition;
        std::vector<std::unique_ptr<statement>> then_code;
        std::vector<std::unique_ptr<statement>> else_code;
        type_id assigned_type;
    };

    struct function_call
    {
        std::string function_name;
        symbol_id symbol_ref;
        std::vector<std::unique_ptr<expr>> arguments;
    };

    struct cast_expression
    {
        std::unique_ptr<expr> expression;
        type_id cast_type;
    };

    struct unary_expression
    {
        std::unique_ptr<expr> expr;
        type_id assigned_type;
    };

    struct binary_expression
    {
        binary_op_t op;
        std::unique_ptr<expr> left;
        std::unique_ptr<expr> right;
        type_id assigned_type;
    };

    struct return_statement
    {
        std::unique_ptr<expr> expression;
        bool is_explicit;
    };

    struct break_statement
    {
    };

    struct expression_statement
    {
        std::unique_ptr<expr> expression;
        bool is_dropped;
    };

    struct store_string_statement
    {
        place target;
        std::size_t string_table_index;
        long long string_size;
    };

    struct store_record_statement
    {
        place target;
        std::vector<field_initialisation> initialisations;
        type_id stored_type;
    };

    struct store_statement
    {
        place target;
        std::unique_ptr<expr> value;
        type_id stored_type;
    };

    struct while_statement
    {
        std::unique_ptr<expr> condition;
        std::vector<std::unique_ptr<statement>> while_code;
    };

    struct function_head : public location
    {
        std::string name;
        function_signature signature;
    };

    struct function_definition : public attributes
    {
        function_head head;
        std::vector<std::unique_ptr<statement>> code;
        std::unique_ptr<scope> function_scope;
    };

    struct import_definition : public location
    {
        std::string ns_name;
        function_head function_head;
        std::optional<std::string> alias;
    };

    struct global_definition : public location
    {
        std::string name;
        type_id assigned_type;
        symbol_id symbol_ref;
        long long init_value;
    };

    struct module : public location
    {
        std::vector<std::unique_ptr<import_definition>> imports;
        std::vector<std::unique_ptr<global_definition>> globals;
        std::vector<std::unique_ptr<function_definition>> functions;
    };

} // namespace lir
