// This file was generated by Silwright.
// Source: lir.ndef
// Generated: 2026-07-13T13:40:23Z
// Do not modify this file directly; regenerate it from the source definition.

#include "lir_visitor.hpp"

#include <cassert>
#include <utility>
#include <variant>

namespace lir
{

    void visitor::visit(expr& value)
    {
        std::visit([this](auto& alternative)
                   { visit(alternative); },
                   value);
    }

    void visitor::visit(statement& value)
    {
        std::visit([this](auto& alternative)
                   { visit(alternative); },
                   value);
    }

    void visitor::visit(number& value)
    {
        enter(value);
        leave(value);
    }

    void visitor::visit(char_literal& value)
    {
        enter(value);
        leave(value);
    }

    void visitor::visit(bool_literal& value)
    {
        enter(value);
        leave(value);
    }

    void visitor::visit(string_literal& value)
    {
        enter(value);
        leave(value);
    }

    void visitor::visit(allocate_record_expression& value)
    {
        enter(value);
        leave(value);
    }

    void visitor::visit(load_expression& value)
    {
        enter(value);
        leave(value);
    }

    void visitor::visit(if_expression& value)
    {
        enter(value);
        if (value.condition)
        {
            visit(*value.condition);
            if (has_expr_replacements_)
            {
                auto replacements_condition = take_expr_replacements();
                assert(replacements_condition.size() <= 1);
                if (replacements_condition.empty())
                {
                    value.condition = nullptr;
                }
                else
                {
                    value.condition = std::move(replacements_condition.front());
                }
            }
        }
        statement_list replacement_then_code;
        replacement_then_code.reserve(value.then_code.size());
        for (auto& child : value.then_code)
        {
            if (!child)
            {
                replacement_then_code.push_back(nullptr);
                continue;
            }
            visit(*child);
            if (has_statement_replacements_)
            {
                auto replacements_then_code = take_statement_replacements();
                for (auto& replacement : replacements_then_code)
                {
                    replacement_then_code.push_back(std::move(replacement));
                }
            }
            else
            {
                replacement_then_code.push_back(std::move(child));
            }
        }
        value.then_code = std::move(replacement_then_code);
        statement_list replacement_else_code;
        replacement_else_code.reserve(value.else_code.size());
        for (auto& child : value.else_code)
        {
            if (!child)
            {
                replacement_else_code.push_back(nullptr);
                continue;
            }
            visit(*child);
            if (has_statement_replacements_)
            {
                auto replacements_else_code = take_statement_replacements();
                for (auto& replacement : replacements_else_code)
                {
                    replacement_else_code.push_back(std::move(replacement));
                }
            }
            else
            {
                replacement_else_code.push_back(std::move(child));
            }
        }
        value.else_code = std::move(replacement_else_code);
        leave(value);
    }

    void visitor::visit(function_call& value)
    {
        enter(value);
        expr_list replacement_arguments;
        replacement_arguments.reserve(value.arguments.size());
        for (auto& child : value.arguments)
        {
            if (!child)
            {
                replacement_arguments.push_back(nullptr);
                continue;
            }
            visit(*child);
            if (has_expr_replacements_)
            {
                auto replacements_arguments = take_expr_replacements();
                for (auto& replacement : replacements_arguments)
                {
                    replacement_arguments.push_back(std::move(replacement));
                }
            }
            else
            {
                replacement_arguments.push_back(std::move(child));
            }
        }
        value.arguments = std::move(replacement_arguments);
        leave(value);
    }

    void visitor::visit(cast_expression& value)
    {
        enter(value);
        if (value.expression)
        {
            visit(*value.expression);
            if (has_expr_replacements_)
            {
                auto replacements_expression = take_expr_replacements();
                assert(replacements_expression.size() <= 1);
                if (replacements_expression.empty())
                {
                    value.expression = nullptr;
                }
                else
                {
                    value.expression = std::move(replacements_expression.front());
                }
            }
        }
        leave(value);
    }

    void visitor::visit(unary_expression& value)
    {
        enter(value);
        if (value.expr)
        {
            visit(*value.expr);
            if (has_expr_replacements_)
            {
                auto replacements_expr = take_expr_replacements();
                assert(replacements_expr.size() <= 1);
                if (replacements_expr.empty())
                {
                    value.expr = nullptr;
                }
                else
                {
                    value.expr = std::move(replacements_expr.front());
                }
            }
        }
        leave(value);
    }

    void visitor::visit(binary_expression& value)
    {
        enter(value);
        if (value.left)
        {
            visit(*value.left);
            if (has_expr_replacements_)
            {
                auto replacements_left = take_expr_replacements();
                assert(replacements_left.size() <= 1);
                if (replacements_left.empty())
                {
                    value.left = nullptr;
                }
                else
                {
                    value.left = std::move(replacements_left.front());
                }
            }
        }
        if (value.right)
        {
            visit(*value.right);
            if (has_expr_replacements_)
            {
                auto replacements_right = take_expr_replacements();
                assert(replacements_right.size() <= 1);
                if (replacements_right.empty())
                {
                    value.right = nullptr;
                }
                else
                {
                    value.right = std::move(replacements_right.front());
                }
            }
        }
        leave(value);
    }

    void visitor::visit(return_statement& value)
    {
        enter(value);
        if (value.expression)
        {
            visit(*value.expression);
            if (has_expr_replacements_)
            {
                auto replacements_expression = take_expr_replacements();
                assert(replacements_expression.size() <= 1);
                if (replacements_expression.empty())
                {
                    value.expression = nullptr;
                }
                else
                {
                    value.expression = std::move(replacements_expression.front());
                }
            }
        }
        leave(value);
    }

    void visitor::visit(break_statement& value)
    {
        enter(value);
        leave(value);
    }

    void visitor::visit(expression_statement& value)
    {
        enter(value);
        if (value.expression)
        {
            visit(*value.expression);
            if (has_expr_replacements_)
            {
                auto replacements_expression = take_expr_replacements();
                assert(replacements_expression.size() <= 1);
                if (replacements_expression.empty())
                {
                    value.expression = nullptr;
                }
                else
                {
                    value.expression = std::move(replacements_expression.front());
                }
            }
        }
        leave(value);
    }

    void visitor::visit(store_string_statement& value)
    {
        enter(value);
        leave(value);
    }

    void visitor::visit(store_record_statement& value)
    {
        enter(value);
        leave(value);
    }

    void visitor::visit(store_statement& value)
    {
        enter(value);
        if (value.value)
        {
            visit(*value.value);
            if (has_expr_replacements_)
            {
                auto replacements_value = take_expr_replacements();
                assert(replacements_value.size() <= 1);
                if (replacements_value.empty())
                {
                    value.value = nullptr;
                }
                else
                {
                    value.value = std::move(replacements_value.front());
                }
            }
        }
        leave(value);
    }

    void visitor::visit(while_statement& value)
    {
        enter(value);
        if (value.condition)
        {
            visit(*value.condition);
            if (has_expr_replacements_)
            {
                auto replacements_condition = take_expr_replacements();
                assert(replacements_condition.size() <= 1);
                if (replacements_condition.empty())
                {
                    value.condition = nullptr;
                }
                else
                {
                    value.condition = std::move(replacements_condition.front());
                }
            }
        }
        statement_list replacement_while_code;
        replacement_while_code.reserve(value.while_code.size());
        for (auto& child : value.while_code)
        {
            if (!child)
            {
                replacement_while_code.push_back(nullptr);
                continue;
            }
            visit(*child);
            if (has_statement_replacements_)
            {
                auto replacements_while_code = take_statement_replacements();
                for (auto& replacement : replacements_while_code)
                {
                    replacement_while_code.push_back(std::move(replacement));
                }
            }
            else
            {
                replacement_while_code.push_back(std::move(child));
            }
        }
        value.while_code = std::move(replacement_while_code);
        leave(value);
    }

    void visitor::visit(function_definition& value)
    {
        enter(value);
        statement_list replacement_code;
        replacement_code.reserve(value.code.size());
        for (auto& child : value.code)
        {
            if (!child)
            {
                replacement_code.push_back(nullptr);
                continue;
            }
            visit(*child);
            if (has_statement_replacements_)
            {
                auto replacements_code = take_statement_replacements();
                for (auto& replacement : replacements_code)
                {
                    replacement_code.push_back(std::move(replacement));
                }
            }
            else
            {
                replacement_code.push_back(std::move(child));
            }
        }
        value.code = std::move(replacement_code);
        leave(value);
    }

    void visitor::visit(import_definition& value)
    {
        enter(value);
        leave(value);
    }

    void visitor::visit(global_definition& value)
    {
        enter(value);
        leave(value);
    }

    void visitor::visit(module& value)
    {
        enter(value);
        for (auto& child : value.imports)
        {
            if (child)
            {
                visit(*child);
            }
        }
        for (auto& child : value.globals)
        {
            if (child)
            {
                visit(*child);
            }
        }
        for (auto& child : value.functions)
        {
            if (child)
            {
                visit(*child);
            }
        }
        leave(value);
    }

    void visitor::enter(number&) {}

    void visitor::leave(number&) {}

    void visitor::enter(char_literal&) {}

    void visitor::leave(char_literal&) {}

    void visitor::enter(bool_literal&) {}

    void visitor::leave(bool_literal&) {}

    void visitor::enter(string_literal&) {}

    void visitor::leave(string_literal&) {}

    void visitor::enter(allocate_record_expression&) {}

    void visitor::leave(allocate_record_expression&) {}

    void visitor::enter(load_expression&) {}

    void visitor::leave(load_expression&) {}

    void visitor::enter(if_expression&) {}

    void visitor::leave(if_expression&) {}

    void visitor::enter(function_call&) {}

    void visitor::leave(function_call&) {}

    void visitor::enter(cast_expression&) {}

    void visitor::leave(cast_expression&) {}

    void visitor::enter(unary_expression&) {}

    void visitor::leave(unary_expression&) {}

    void visitor::enter(binary_expression&) {}

    void visitor::leave(binary_expression&) {}

    void visitor::enter(return_statement&) {}

    void visitor::leave(return_statement&) {}

    void visitor::enter(break_statement&) {}

    void visitor::leave(break_statement&) {}

    void visitor::enter(expression_statement&) {}

    void visitor::leave(expression_statement&) {}

    void visitor::enter(store_string_statement&) {}

    void visitor::leave(store_string_statement&) {}

    void visitor::enter(store_record_statement&) {}

    void visitor::leave(store_record_statement&) {}

    void visitor::enter(store_statement&) {}

    void visitor::leave(store_statement&) {}

    void visitor::enter(while_statement&) {}

    void visitor::leave(while_statement&) {}

    void visitor::enter(function_definition&) {}

    void visitor::leave(function_definition&) {}

    void visitor::enter(import_definition&) {}

    void visitor::leave(import_definition&) {}

    void visitor::enter(global_definition&) {}

    void visitor::leave(global_definition&) {}

    void visitor::enter(module&) {}

    void visitor::leave(module&) {}

    void visitor::replace_expr(std::unique_ptr<expr> replacement)
    {
        has_expr_replacements_ = true;
        expr_replacements_.clear();
        expr_replacements_.push_back(std::move(replacement));
    }

    void visitor::replace_expr(expr_list replacements)
    {
        has_expr_replacements_ = true;
        expr_replacements_ = std::move(replacements);
    }

    expr_list visitor::take_expr_replacements()
    {
        has_expr_replacements_ = false;
        return std::move(expr_replacements_);
    }

    void visitor::replace_statement(std::unique_ptr<statement> replacement)
    {
        has_statement_replacements_ = true;
        statement_replacements_.clear();
        statement_replacements_.push_back(std::move(replacement));
    }

    void visitor::replace_statement(statement_list replacements)
    {
        has_statement_replacements_ = true;
        statement_replacements_ = std::move(replacements);
    }

    statement_list visitor::take_statement_replacements()
    {
        has_statement_replacements_ = false;
        return std::move(statement_replacements_);
    }

} // namespace lir
